# Generated by Django 5.2.3 on 2025-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consent_given',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='consent_given_at',
        ),
        migrations.AddField(
            model_name='client',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AddField(
            model_name='client',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения согласия'),
        ),
    ]
