# Generated by Django 5.2.3 on 2025-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coloring", "Окрашивание"),
                            ("haircut", "Стрижка и укладка"),
                            ("manicure", "Маникюр"),
                            ("pedicure", "Педикюр"),
                            ("makeup", "Макияж"),
                            ("other", "Другое"),
                        ],
                        max_length=100,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="Длительность (минуты)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["category", "name"],
            },
        ),
    ]
