# Generated by Django 5.2.3 on 2025-06-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0002_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "specialization",
                    models.CharField(max_length=200, verbose_name="Специализация"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masters",
                        to="salon.salon",
                        verbose_name="Салон",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="masters",
                        to="salon.service",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
