# Generated by Django 5.2.3 on 2025-06-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чаевые'),
        ),
    ]
